---

- import_playbook: playbook_pre_tasks.yml
- import_playbook: playbook_launch_instance.yml

- name: Configure Servers
  hosts: launched
  user: core
  gather_facts: False

  roles:
    - akirak.coreos-python

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks: 
    - name: Setup Docker, Setup Neo, Run Loader, Push Images
      block:
        - include_tasks: tasks/install_docker_py.yml
        - include_tasks: tasks/setup_docker.yml
