---

- import_playbook: playbook_pre_tasks.yml
- import_playbook: playbook_launch_web_instance.yml

- name: configure servers
  hosts: launched
  user: core
  gather_facts: false

  roles:
    - install_python

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks:
    - name: Setup Docker, Setup Neo, Run Loader, Push Images
      block:
        - include_tasks: tasks/setup_swap.yml
        - include_tasks: tasks/setup_docker.yml
        - include_tasks: tasks/start_elk.yml
