---

- import_playbook: pre_tasks_playbook.yml
- import_playbook: launch_instance_playbook.yml

- name: Configure Servers
  hosts: launched
  user: core
  gather_facts: False

  roles:
    - akirak.coreos-python

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks: 
    - name: Setup Neo, Run Loader, Run Loader Tests
      block:
        - include_tasks: tasks/install_docker_py.yml
        - include_tasks: tasks/docker_setup.yml
        - include_tasks: tasks/start_neo_env.yml
        - include_tasks: tasks/loader_test_run.yml

      rescue:
        - fail:
           msg: 'Tasked Failed Terminating instances'

- import_playbook: terminate_instance_playbook.yml
