- name: Launch Monitoring
  hosts: launched
  user: core
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks:
    - name: Start Monitoring
      debugger: on_failed
      block:
        - include_tasks: tasks/start_monitoring.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"