---
- name: Terminations
  hosts: local
  connection: local
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"

  tasks:
    - name: Terminate instances
      ec2_instance:
        state: 'absent'
        region: us-east-1
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        instance_ids: '{{ ec2_result.instance_ids }}'
