---

- import_playbook: playbook_pre_tasks.yml
- import_playbook: playbook_launch_instance.yml

- name: Configure Servers
  hosts: launched
  user: core
  gather_facts: False

  roles:
    - akirak.coreos-python

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  tasks: 
    - name: Setup Docker, Start Neo, Run File Generator
      block:
        - include_tasks: tasks/install_docker_py.yml
        - include_tasks: tasks/setup_docker.yml
        - include_tasks: tasks/start_neo_data.yml
        - include_tasks: tasks/run_file_gener.yml

      rescue:
        - debug:
           msg: 'Tasked Failed Terminating instances'

- import_playbook: playbook_terminate_instance.yml
