---

- import_playbook: playbook_pre_tasks.yml
- import_playbook: playbook_launch_instance.yml

- name: Configure Servers
  hosts: launched
  user: core
  gather_facts: False

  roles:
    - akirak.coreos-python

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  vars:
    API_ACCESS_TOKEN: "{{ LOADER_BUILD_API_ACCESS_TOKEN if env == 'build' else LOADER_STAGE_API_ACCESS_TOKEN }}"

  tasks:
    - name: Setup Neo, Run Loader, Run Loader Tests
      block:
        - include_tasks: tasks/install_docker_py.yml
        - include_tasks: tasks/setup_docker.yml
        - include_tasks: tasks/start_neo_env.yml
        - include_tasks: tasks/run_loader_integration_tests.yml
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"

- import_playbook: playbook_terminate_instance.yml

- name: Check Failures
  hosts: launched
  gather_facts: False
  tasks:
    - fail:
        msg: "The execution has failed because of errors."
      when: failed_flag == "failed"

