- name: Launch Post Tasks
  hosts: launched
  user: core
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"
    - "environments/shared_aws_instance_variables.yml"

  roles:
    - role: install_python
      become: true
      become_user: root
    - role: setup_nvme_drives
      when: not SKIP_NVME_DRIVES and not SETUP_NVME_DRIVE
      become: true
      become_user: root
    - role: setup_nvme_drive
      when: SETUP_NVME_DRIVE and SKIP_NVME_DRIVES
      become: true
      become_user: root
    - role: setup_docker # setup_nvme_drive(s) restarts docker so this needs to come after
      become: true
      become_user: root
    - role: setup_swap
      become: true
      become_user: root

  tasks:
    - name: Setup Docker, Start ES, Start Neo, Run Indexer
      debugger: on_failed
      block:
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"
