---

- import_playbook: playbook_launch_pre_tasks.yml
- import_playbook: playbook_launch_instance.yml
- import_playbook: playbook_launch_post_tasks.yml

- name: Configure Servers
  hosts: launched
  user: core
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  vars:
    API_ACCESS_TOKEN: "{{ LOADER_BUILD_API_ACCESS_TOKEN if env == 'build' else LOADER_STAGE_API_ACCESS_TOKEN }}"

  tasks:
    - name: Setup Neo, Run Loader, Push Images
      block:
        - include_tasks: tasks/start_intermine.yml
        - set_fact:
            failed_flag: "passed"

      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"

- name: Check Failures
  hosts: launched
  gather_facts: False
  tasks:
    - fail:
        msg: "The execution has failed because of errors."
      when: failed_flag == "failed"
