- name: Launch Post Tasks
  hosts: launched
  user: core
  gather_facts: False

  vars_files:
    - "environments/{{ env }}/main.yml" # ENV must always be loaded first
    - "environments/shared_secrets.yml"
    - "environments/shared_variables.yml"

  roles:
    - role: install_python
      become: true
      become_user: root
    - role: setup_nvme_drives
      when: SKIP_NVME_DRIVES == false
      become: true
      become_user: root
    - role: setup_docker
      become: true
      become_user: root
    - role: setup_swap
      become: true
      become_user: root

  tasks:
    - name: Setup Docker, Start ES, Start Neo, Run Indexer, Start Prometheus, Start Grafana
      block:
        - set_fact:
            failed_flag: "passed"
      rescue:
        - debug:
            msg: "Error Detected Failing Build"
        - set_fact:
            failed_flag: "failed"
