---
- name: Setup Docker Server
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Launch instances
      ec2:
        key_name: AGR-ssl2
        keypair: AGR-ssl2
        group: default, ES Transport, HTTP, HTTPS SSL, SSH
        instance_type: m1.small
        image: ami-0b1db01d775d666c2
        wait: true
        region: us-east-1
        #vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
        count: 1
      register: ec2

    - name: Wait for SSH to be up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instanes }}"

    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
