- name: Pull Java Testing Run Image
  docker_image:
    name: "{{ API_TEST_IMAGE_NAME }}"

- name: Run API
  docker_container:
    name: "{{ API_SERVER_NAME }}"
    image: "{{ API_TEST_IMAGE_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: udp://logs.alliancegenome.org:12201
    networks:
      - name: "{{ NET }}"
    command: java -jar agr_api/target/agr_api-thorntail.jar
    env:
      NEO4J_HOST: "{{ NEO_TESTING_SERVER_NAME }}"
      CACHE_HOST: "{{ CACHE_TESTING_SERVER_NAME }}"
      ES_HOST: "{{ ES_TESTING_SERVER_NAME }}"

- pause:
    minutes: 1

- name: Run API Tests
  docker_container:
    name: "{{ API_TEST_NAME }}"
    image: "{{ API_TEST_IMAGE_NAME }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: udp://logs.alliancegenome.org:12201
    networks:
      - name: "{{ NET }}"
    command: mvn -B verify -pl agr_api -am
    env:
      API_HOST: "{{ API_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_TESTING_SERVER_NAME }}"
      CACHE_HOST: "{{ CACHE_TESTING_SERVER_NAME }}"
      ES_HOST: "{{ ES_TESTING_SERVER_NAME }}"

