- name: Download JBrowse Deploy Repo
  git:
    repo: 'https://github.com/alliance-genome/agr_stage_jbrowse_ebdeploy.git'
    dest: /tmp/agr_stage_jbrowse_ebdeploy
    version: main

- name: Deploy JBrowse to EBS
  command: eb deploy stage-jbrowse --timeout 30
  args:
    chdir: /tmp/agr_stage_jbrowse_ebdeploy

- name: Remove agr_stage_jbrowse_ebdeploy directory
  shell:
    cmd: rm -fr agr_stage_jbrowse_ebdeploy
    chdir: /tmp
