- name: Download API Deploy Repo
  git:
    repo: 'https://github.com/alliance-genome/agr_production_api_ebdeploy.git'
    dest: /tmp/agr_production_api_ebdeploy
    version: main

- name: Set Alliance Release Version "{{ ALLIANCE_RELEASE }}"
  command: sed -i.bak "s/0.0.0/{{ ALLIANCE_RELEASE }}/g" .ebextensions/env.config
  args:
    chdir: /tmp/agr_production_api_ebdeploy

- name: Deploy API to EBS
  command: eb deploy production-quarkus-api --timeout 30
  args:
    chdir: /tmp/agr_production_api_ebdeploy

- name: Remove agr_production_api_ebdeploy directory
  shell:
    cmd: rm -fr agr_production_api_ebdeploy
    chdir: /tmp
