- name: Download API Deploy Repo
  git:
    repo: 'https://github.com/alliance-genome/agr_stage_api_ebdeploy.git'
    dest: /tmp/agr_stage_api_ebdeploy
    version: main

- name: Deploy API to EBS
  command: eb deploy stage-quarkus-api --timeout 30
  args:
    chdir: /tmp/agr_stage_api_ebdeploy

- name: Remove agr_stage_api_ebdeploy directory
  shell:
    cmd: rm -fr agr_stage_api_ebdeploy
    chdir: /tmp
