- name: Download Tomcat Deploy Repo
  git:
    repo: 'https://github.com/alliance-genome/agr_intermine_tomcat_ebdeploy.git'
    dest: /tmp/agr_intermine_tomcat_ebdeploy
    version: main

- name: Deploy Tomcat to EBS
  command: eb deploy stage-intermine-tomcat --timeout 30
  args:
    chdir: /tmp/agr_intermine_tomcat_ebdeploy

- name: Remove agr_intermine_tomcat_ebdeploy directory
  shell:
    cmd: rm -fr agr_intermine_tomcat_ebdeploy
    chdir: /tmp
