- name: Pull File Generator Run Image
  docker_image:
    name: "{{ FILE_GENER_RUN_IMAGE_NAME }}"

- name: Run File Generator
  docker_container:
    name: "{{ FILE_GENER_RUN_NAME }}"
    image: "{{ FILE_GENER_RUN_IMAGE_NAME }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: udp://logs.alliancegenome.org:12201
    networks:
      - name: "{{ NET }}"
    env:
      FMS_API_URL: "{{ FMS_API_URL }}"
      API_KEY: "{{ API_ACCESS_TOKEN }}"
      RELEASE_VERSION: "{{ ALLIANCE_RELEASE }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
