
- name: Stop Tomcat
  docker_container:
    name: "{{ INTERMINE_TOMCAT_SERVER_NAME }}"
    state: stopped

- name: Stop Solr
  docker_container:
    name: "{{ INTERMINE_SOLR_SERVER_NAME }}"
    state: stopped

- name: Stop Postgres
  docker_container:
    name: "{{ INTERMINE_POSTGRES_SERVER_NAME }}"
    state: stopped

- name: Commit Tomcat container
  command: docker commit "{{ INTERMINE_TOMCAT_SERVER_NAME }}" "{{ INTERMINE_TOMCAT_SERVER_IMAGE_NAME }}"
- name: Push Tomcat Container
  command: docker push "{{ INTERMINE_TOMCAT_SERVER_IMAGE_NAME }}"

- name: Commit Solr container
  command: docker commit "{{ INTERMINE_SOLR_SERVER_NAME }}" "{{ INTERMINE_SOLR_SERVER_IMAGE_NAME }}"
- name: Push Solr Container
  command: docker push "{{ INTERMINE_SOLR_SERVER_IMAGE_NAME }}"

- name: Commit Postgres container
  command: docker commit "{{ INTERMINE_POSTGRES_SERVER_NAME }}" "{{ INTERMINE_POSTGRES_SERVER_IMAGE_NAME }}"
- name: Push Postgres Container
  command: docker push "{{ INTERMINE_POSTGRES_SERVER_IMAGE_NAME }}"
