- name: Stop Cacher
  docker_container:
    name: "{{ INFINISPAN_SERVER_NAME }}"
    state: stopped

- name: Commit container
  command: docker commit "{{ INFINISPAN_SERVER_NAME }}" "{{ CACHER_RELEASE_REG_INAME }}:{{ DOCKER_BUILD_TAG }}"

- name: Push Container To Docker Hub
  command: docker push "{{ CACHER_RELEASE_REG_INAME }}:{{ DOCKER_BUILD_TAG }}"
