- name: Stop Cacher
  docker_container:
    name: "{{ INFINISPAN_SERVER_NAME }}"
    state: stopped

- name: Commit container
  command: docker commit "{{ INFINISPAN_SERVER_NAME }}" "{{ CACHER_DATA_BUILD_IMAGE }}"

- name: Push Container To Docker Hub
  command: docker push "{{ CACHER_DATA_BUILD_IMAGE }}"
