
- name: Stop Tomcat
  docker_container:
    name: "{{ INTERMINE_TOMCAT_SERVER_NAME }}"
    state: stopped

- name: Stop Solr
  docker_container:
    name: "{{ INTERMINE_SOLR_SERVER_NAME }}"
    state: stopped

- name: Stop Postgres
  docker_container:
    name: "{{ INTERMINE_POSTGRES_SERVER_NAME }}"
    state: stopped

- name: Commit Tomcat container
  command: docker commit "{{ INTERMINE_TOMCAT_SERVER_NAME }}" "{{ INTERMINE_TOMCAT_SERVER_IMAGE_NAME }}"
- name: Push Tomcat Container
  command: docker push "{{ INTERMINE_TOMCAT_SERVER_IMAGE_NAME }}"
- name: Tag Tomcat NET Container
  command: docker tag "{{ INTERMINE_TOMCAT_SERVER_IMAGE_NAME }}" "{{ INTERMINE_TOMCAT_NETWORK_IMAGE_NAME }}"
  when: NET != DOCKER_IMAGE_TAG
- name: Push Tomcat NET Container
  command: docker push "{{ INTERMINE_TOMCAT_NETWORK_IMAGE_NAME }}"
  when: NET != DOCKER_IMAGE_TAG

- name: Commit Solr container
  command: docker commit "{{ INTERMINE_SOLR_SERVER_NAME }}" "{{ INTERMINE_SOLR_SERVER_IMAGE_NAME }}"
- name: Push Solr Container
  command: docker push "{{ INTERMINE_SOLR_SERVER_IMAGE_NAME }}"
- name: Tag Solr NET Container
  command: docker tag "{{ INTERMINE_SOLR_SERVER_IMAGE_NAME }}" "{{ INTERMINE_SOLR_NETWORK_IMAGE_NAME}}"
  when: NET != DOCKER_IMAGE_TAG
- name: Push Solr NET Container
  command: docker push "{{ INTERMINE_SOLR_NETWORK_IMAGE_NAME }}"
  when: NET != DOCKER_IMAGE_TAG

- name: Commit Postgres container
  command: docker commit "{{ INTERMINE_POSTGRES_SERVER_NAME }}" "{{ INTERMINE_POSTGRES_SERVER_IMAGE_NAME }}"
- name: Push Postgres Container
  command: docker push "{{ INTERMINE_POSTGRES_SERVER_IMAGE_NAME }}"
- name: Tag Postgres NET Container
  command: docker tag "{{ INTERMINE_POSTGRES_SERVER_IMAGE_NAME }}" "{{ INTERMINE_POSTGRES_NETWORK_IMAGE_NAME }}"
  when: NET != DOCKER_IMAGE_TAG
- name: Push Postgres NET Container
  command: docker push "{{ INTERMINE_POSTGRES_NETWORK_IMAGE_NAME }}"
  when: NET != DOCKER_IMAGE_TAG
