
- name: Stop Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    state: stopped

- name: Commit container
  command: docker commit "{{ NEO_SERVER_NAME }}" "{{ NEO_RELEASE_IMAGE_NAME }}"

- name: Push Container
  command: docker push "{{ NEO_RELEASE_IMAGE_NAME }}"

- name: Tag NET Container
  command: docker tag "{{ NEO_RELEASE_IMAGE_NAME }}" "{{ NEO_NETWORK_IMAGE_NAME }}"

- name: Push NET Container
  command: docker push "{{ NEO_NETWORK_IMAGE_NAME }}"
