- name: Pull Indexer Run Image
  shell: docker pull {{ JAVA_SOFTWARE_RUN_IMAGE }} 2>&1

- name: Run Indexer
  docker_container:
    name: "{{ INDEXER_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    detach: no
    timeout: 25000
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
      ES_INDEX_SUFFIX: "{{ NET }}"
      ES_SHARD_COUNT: "8"
      BLUETEAM_ES_URL: "{{ BLUETEAM_ES_URL }}"
      CURATION_API_URL: "{{ CURATION_API_URL }}"
      CURATION_API_TOKEN: "{{ CURATION_API_TOKEN }}"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      AGR_EXCEPTIONAL_ENDPOINT: "https://exceptions.alliancegenome.org"
      AGR_EXCEPTIONAL_SERVICE: "Indexer"
      BOLT_LOG_LEVEL: INFO
      DEFAULT_LOG_LEVEL: INFO
      ES_HOST: "{{ ES_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+ParallelRefProcEnabled -DTHREADED={{ THREADED }} -jar agr_indexer/target/agr_indexer-jar-with-dependencies.jar

- name: Run File Generator
  docker_container:
    name: "agr.{{ env }}.file_generator"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    detach: no
    timeout: 25000
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      AWS_BUCKET_NAME: "{{ FILE_GENER_BUCKET_NAME }}"
      ES_HOST: "{{ ES_SERVER_NAME }}"
      ES_INDEX: "site_index_{{ NET }}_temp"
      CURATION_API_URL: "{{ CURATION_API_URL }}"
      CURATION_API_TOKEN: "{{ CURATION_API_TOKEN }}"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      GENERATED_FILES_FOLDER: "/tmp/agr_file_generator"
      AGR_EXCEPTIONAL_ENDPOINT: "https://exceptions.alliancegenome.org"
      AGR_EXCEPTIONAL_SERVICE: "FileGenerator"
    command: java -Xms28G -Xmx28G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+ParallelRefProcEnabled -jar agr_file_generator/target/agr_file_generator-jar-with-dependencies.jar

