- name: Run Loader Tests against Neo
  docker_container:
    name: "{{ LOADER_RUN_NAME }}"
    image: "{{ LOADER_RUN_IMAGE }}"
    command: pytest --verbose --workers 8
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    volumes:
      - "{{ NEO_VOLUME_NAME }}:/usr/src/app/tmp"
    network_mode: "{{ NET }}"
    env:
      DOWNLOAD_HOST: "{{ DOWNLOAD_HOST }}"
      TEST_SET: "{{ LOADER_TEST_SET }}"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      FMS_API_URL: "{{ FMS_API_URL }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
