- name: Pull Preprocess Run Image
  docker_image:
    name: "{{ PREPROCESS_RUN_IMAGE }}"

- name: Run Preprocess
  docker_container:
    name: "{{ PREPROCESS_RUN_NAME }}"
    image: "{{ PREPROCESS_RUN_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    networks_cli_compatible: no
    env:
      API_KEY: "{{ API_ACCESS_TOKEN }}"
      DEBUG: "False"
      DOWNLOAD_HOST: "{{ DOWNLOAD_HOST }}"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      FMS_API_URL: "{{ FMS_API_URL }}"
