- name: Pull Java Software Run Image
  shell: docker pull {{ JAVA_SOFTWARE_RUN_IMAGE }} 2>&1

- name: Run Variant Indexer
  docker_container:
    name: "{{ VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    detach: no
    timeout: 43200
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
      ES_INDEX: "variant_index"
      ES_INDEX_SUFFIX: "{{ NET }}"
      CURATION_API_URL: "{{ CURATION_API_URL }}"
      CURATION_API_TOKEN: "{{ CURATION_API_TOKEN }}"
      VARIANT_INDEXER_SHARDS: "4"
      VARIANT_SOURCE_DOCUMENT_CREATOR_THREADS: "8"
      VARIANT_BULK_PROCESSOR_SETTINGS: "10000;4;10;10000;1000,133;4;10;1333;7500,100;4;10;1000;10000,50;4;10;500;10000000"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      AGR_EXCEPTIONAL_ENDPOINT: "https://exceptions.alliancegenome.org"
      AGR_EXCEPTIONAL_SERVICE: "VariantIndexer"
      ES_HOST: "{{ ES_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"

    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar
