- name: Pull Java Software Run Image
  docker_image:
    name: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"

- name: Run Human Variant Indexer
  docker_container:
    name: "{{ HUMAN_VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
    env:
      AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
      ES_INDEX_PREFIX: "human"
      ES_INDEX: "variant_index"
      ES_INDEX_SUFFIX: "{{ NET }}"
      VARIANTS_TO_INDEX: "HUMAN"
      VARIANT_INDEXER_SHARDS: "64"
      VARIANT_SOURCE_DOCUMENT_CREATOR_VCQUEUE_SIZE: "400"
      VARIANT_SOURCE_DOCUMENT_CREATOR_VCQUEUE_BUCKET_SIZE: "25"
      VARIANT_SOURCE_DOCUMENT_CREATOR_OBJECT_QUEUE_SIZE: "500"
      VARIANT_SOURCE_DOCUMENT_CREATOR_OBJECT_QUEUE_BUCKET_SIZE: "50"
      VARIANT_PRODUCER_THREADS: "12"
      
      VARIANT_TRANSFORMER_THREADS: "12"
      VARIANT_INDEXER_BULK_PROCESSOR_THREADS: "10"
      VARIANT_BULK_PROCESSOR_SETTINGS: "10000;20;10;1500;1000,133;20;10;1333;7500,100;20;10;1000;10000,50;20;10;500;10000000"

      ES_HOST: "{{ hostvars['all_hosts']['node_http_list'] }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"

    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar
