- name: Pull Variant Indexer Run Image
  docker_image:
    name: "{{ VARIANT_RUN_IMAGE }}"

- name: Run Variant Indexer
  docker_container:
    name: "{{ VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ VARIANT_RUN_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
    volumes:
      - "/data:/data"
    env:
      ES_INDEX_SUFFIX: "{{ NET }}"
      ES_INDEX_PREFIX: "human"
      ES_INDEX: variant_index
      THREADED: "{{ THREADED }}"

      VARIANT_INDEXER_SHARDS: 128

      #ES_HOST: "{{ hostvars['all_hosts']['node_list'] }}"
      ES_HOST: "18.234.155.116:9201,18.234.155.116:9202,54.81.196.192:9203,54.81.196.192:9204,18.209.32.14:9205,18.209.32.14:9206,34.226.204.228:9207,34.226.204.228:9208"

    command: java -DVARIANTS_TO_INDEX="HUMAN" -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar

