- name: Pull Intermine Builder Image
  docker_image:
    name: "{{ INTERMINE_BUILDER_RUN_IMAGE }}"
    source: pull

- name: Pull Java Run Image
  docker_image:
    name: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    source: pull

- name: Run Java Intermine Data Extractor
  docker_container:
    name: "{{ INTERMINE_DATA_EXTRACTOR_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    volumes:
      - "{{ INTERMINE_DATA_VOLUME_NAME }}:/data"
    env:
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      EXTRACTOR_OUTPUTDIR: "/data"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -DDEFAULT_LOG_LEVEL=DEBUG -jar agr_intermine_data_extractor/target/agr_intermine_data_extractor-jar-with-dependencies.jar

- name: Run Intermine Builder
  docker_container:
    name: "{{ INTERMINE_BUILDER_RUN_NAME }}"
    image: "{{ INTERMINE_BUILDER_RUN_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    volumes:
      - "{{ INTERMINE_DATA_VOLUME_NAME }}:/root/data"
    network_mode: "{{ NET }}"
    command: ./build_db_all postgres postgres
