---

- name: Pull Java Run Image
  docker_image:
    name: "{{ JAVA_SOFTWARE_RUN_IMAGE_NAME }}"

- name: Restore Latest ES Snapshot
  docker_container:
    name: "agr.{{ NET }}.restore_es.run"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOGSTASH_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
    command: java -jar agr_elasticsearch_util/target/agr_elasticsearch_util-jar-with-dependencies.jar snapshot restorelatest "{{ REPO }}"
    env:
      AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
      AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
      CACHE_HOST: "{{ INFINISPAN_SERVER_NAME }}"
      ES_HOST: "{{ ES_SERVER_NAME }}"


