- name: Pull Java Software Run Image
  docker_image:
    name: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    source: pull

- name: Run Human Variant Indexer
  docker_container:
    name: "{{ HUMAN_VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    timeout: 43200
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
      ES_INDEX_PREFIX: "human"
      ES_INDEX: "variant_index"
      ES_INDEX_SUFFIX: "{{ NET }}"
      VARIANTS_TO_INDEX: "HUMAN"
      VARIANT_INDEXER_SHARDS: "4"
      VARIANT_SOURCE_DOCUMENT_CREATOR_VCQUEUE_SIZE: "400"
      VARIANT_SOURCE_DOCUMENT_CREATOR_VCQUEUE_BUCKET_SIZE: "25"
      VARIANT_SOURCE_DOCUMENT_CREATOR_OBJECT_QUEUE_SIZE: "450"
      VARIANT_SOURCE_DOCUMENT_CREATOR_OBJECT_QUEUE_BUCKET_SIZE: "32"
      VARIANT_PRODUCER_THREADS: "12"
      
      VARIANT_TRANSFORMER_THREADS: "12"
      VARIANT_INDEXER_BULK_PROCESSOR_THREADS: "12"
      VARIANT_BULK_PROCESSOR_SETTINGS: "10000;20;10;1500;7500,133;20;10;1333;15000,100;20;10;1000;30000,50;20;10;500;10000000"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"

      ES_HOST: "{{ ES_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"

    command: java -Xms{{ INDEXER_MEMORY }} -Xmx{{ INDEXER_MEMORY }} -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar
