- name: Run Loader Tests against Neo
  docker_container:
    name: "{{ LOADER_RUN_NAME }}"
    image: "{{ LOADER_RUN_IMAGE }}"
    command: conda run -n agr_loader --no-capture-output pytest --verbose --workers 8
    detach: no
    timeout: 25000
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      DOWNLOAD_HOST: "{{ DOWNLOAD_HOST }}"
      TEST_SET: "{{ LOADER_TEST_SET }}"
      ALLIANCE_RELEASE: "{{ ALLIANCE_RELEASE }}"
      FMS_API_URL: "{{ FMS_API_URL }}"
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
