- name: Pull Java Testing Run Image
  shell: docker pull {{ INDEXER_TEST_IMAGE }} 2>&1

- name: Run Indexer Tests
  docker_container:
    name: "{{ INDEXER_TEST_NAME }}"
    image: "{{ INDEXER_TEST_IMAGE }}"
    detach: no
    timeout: 25000
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    command: mvn -B verify -pl agr_indexer -am
    env:
      API_HOST: "{{ API_TESTING_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_TESTING_SERVER_NAME }}"
      CACHE_HOST: "{{ CACHE_TESTING_SERVER_NAME }}"
      ES_HOST: "{{ ES_TESTING_SERVER_NAME }}"
      API_SECURE: "true"
