- name: Pull Variant Indexer Run Image
  docker_image:
    name: "{{ VARIANT_RUN_IMAGE }}"

- name: Debug
  debug:
    msg: "{{ hostvars['all_hosts'] }}"

- name: Run Variant Indexer
  docker_container:
    name: "{{ VARIANT_INDEXER_RUN_NAME }}"
    image: "{{ VARIANT_RUN_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
    env:
      ES_INDEX_SUFFIX: "{{ NET }}"
      ES_INDEX_PREFIX: "human"
      ES_INDEX: "variant_index"

      DVARIANTS_TO_INDEX: "HUMAN"

      VARIANT_INDEXER_SHARDS: "64"

      ES_HOST: "{{ hostvars['all_hosts']['node_http_list'] }}"

    command: java -jar agr_variant_indexer/target/agr_variant_indexer-jar-with-dependencies.jar
