- name: Pull Java Testing Run Image
  docker_image:
    name: "{{ INDEXER_TEST_IMAGE_NAME }}"

- name: Run Indexer Tests
  docker_container:
    name: "{{ INDEXER_TEST_NAME }}"
    image: "{{ INDEXER_TEST_IMAGE_NAME }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
    command: mvn -B verify -pl agr_indexer -am
    env:
      API_HOST: "{{ API_TESTING_SERVER_NAME }}"
      NEO4J_HOST: "{{ NEO_TESTING_SERVER_NAME }}"
      CACHE_HOST: "{{ CACHE_TESTING_SERVER_NAME }}"
      ES_HOST: "{{ ES_TESTING_SERVER_NAME }}"
      API_SECURE: "true"
