---

- name: Pull Nginx Server Image
  docker_image:
    name: "{{ REGISTRY }}/agr_nginx:{{ NGINX_TAG }}"
    source: pull

- name: Run Nginx
  docker_container:
    name: "agr.{{ NET }}.nginx.server"
    image: "{{ REGISTRY }}/agr_nginx:{{ NGINX_TAG }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "80:80"
      - "443:443"
    network_mode: "{{ NET }}"
    env:
      API_URL: "http://{{ API_SERVER_NAME }}:8080"
    volumes:
      - /home/core/.htpasswd:/etc/nginx/.htpasswd
      - /home/core/ssl:/etc/ssl/certs
