- name: Pull Intermine Solr Env Image
  docker_image:
    name: "{{ INTERMINE_SOLR_ENV_NAME }}"
    source: pull

- name: Run Solr
  docker_container:
    name: "{{ INTERMINE_SOLR_SERVER_NAME }}"
    image: "{{ INTERMINE_SOLR_ENV_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
#    volumes:
#      - "{{ NEO_VOLUME_NAME }}:/var/lib/neo4j/import"
    network_mode: "{{ NET }}"
    env:
      MINE_NAME: "alliancemine"
      MEM_OPTS: "-Xmx2g -Xms1g"
      JAVA_OPTS: "-Dorg.apache.el.parser.SKIP_IDENTIFIER_CHECK=true -Xmx2g -Xms1g -XX:+UseParallelGC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:MaxHeapFreeRatio=99"
