---

- name: Pull JBrowse Server Image
  shell: docker pull {{ JBROWSE_SERVER_IMAGE }} 2>&1

- name: Run JBrowse Server
  docker_container:
    name: "{{ JBROWSE_SERVER_NAME }}"
    image: "{{ JBROWSE_SERVER_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
