- name: Pull Intermine CDN Image
  docker_image:
    name: "{{ INTERMINE_CDN_SERVER_IMAGE }}"

- name: Run CDN Nginx container
  docker_container:
    name: "{{ INTERMINE_CDN_SERVER_NAME }}"
    image: "{{ INTERMINE_CDN_SERVER_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
