- name: Pull Neo4j Env Image
  docker_image:
    name: "{{ NEO_ENV_IMAGE_NAME }}"

- name: Create Neo4j Shared Volume
  docker_volume:
    name: "{{ NEO_VOLUME_NAME }}"

- name: Run Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_ENV_IMAGE_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "udp://{{ GELF_LOG_SERVER_NAME }}:12201"
    volumes:
      - "{{ NEO_VOLUME_NAME }}:/var/lib/neo4j/import"
    networks:
      - name: "{{ NET }}"
    env:
      NEO4J_dbms_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      NEO4J_dbms_memory_heap_maxSize: "{{ NEO_MAX_HEAP }}"
      NEO4J_AUTH: "none"
