- name: Pull ES Env Image
  docker_image:
    name: "{{ ES_ENV_IMAGE }}"
    source: pull

- name: Pull Cerebro Image
  docker_image:
    name: "yannart/cerebro:latest"
    source: pull

- name: Run ES
  docker_container:
    name: "{{ ES_SERVER_NAME }}"
    image: "{{ ES_ENV_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    ports:
      - "9200:9200"
      - "9300:9300"
    env:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms{{ ES_CLUSTER_MEMORY }} -Xmx{{ ES_CLUSTER_MEMORY }}"

- name: Run Cerebro
  docker_container:
    name: "agr.{{ env }}.cerebro.server"
    image: "yannart/cerebro:latest"
    network_mode: "{{ NET }}"
    ports:
      - "9000:9000"
