---

- name: Pull JBrowse Server Image
  docker_image:
    name: "{{ JBROWSE_SERVER_IMAGE }}"
    source: pull

- name: Run JBrowse Server
  docker_container:
    name: "{{ JBROWSE_SERVER_NAME }}"
    image: "{{ JBROWSE_SERVER_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
