- name: Pull Neo4j Env Image
  docker_image:
    name: "{{ NEO_ENV_IMAGE }}"
    source: pull

- name: Run Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_ENV_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    volumes:
      - "{{ NEO_VOLUME_NAME }}:/var/lib/neo4j/import"
    network_mode: "{{ NET }}"
    env:
      NEO4J_server_memory_heap_max__size: "{{ NEO_MAX_HEAP }}"
      NEO4J_server_memory_heap_initial__size: "{{ NEO_MAX_HEAP }}"
      NEO4J_server_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      NEO4J_AUTH: "none"
