---

- name: Pull UI Server Image
  docker_image:
    name: "{{ UI_SERVER_IMAGE }}"
    source: pull

- name: Run UI
  docker_container:
    name: "{{ UI_SERVER_NAME }}"
    image: "{{ UI_SERVER_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      API_URL: "http://{{ API_SERVER_NAME }}:8080"
