---

- name: Pull Apollo Server Image
  shell: docker pull {{ APOLLO_SERVER_IMAGE }} 2>&1

- name: Run Apollo Server
  docker_container:
    name: "{{ APOLLO_SERVER_NAME }}"
    image: "{{ APOLLO_SERVER_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      APOLLO_PATH: apollo
