- name: Pull Neo4j Data Image
  docker_image:
    name: "{{ NEO_RELEASE_IMAGE_NAME }}"

- name: Run Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_RELEASE_IMAGE_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: udp://logs.alliancegenome.org:12201
    networks:
      - name: "{{ NET }}"
    env:
      NEO4J_dbms_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      NEO4J_dbms_memory_heap_maxSize: "{{ NEO_MAX_HEAP }}"
      NEO4J_AUTH: "none" 

- pause:
    minutes: 2
