- name: Pull Intermine CDN Image
  shell: docker pull {{ INTERMINE_CDN_SERVER_IMAGE }} 2>&1

- name: Run CDN Nginx container
  docker_container:
    name: "{{ INTERMINE_CDN_SERVER_NAME }}"
    image: "{{ INTERMINE_CDN_SERVER_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
