- name: Pull Infinispan Env Image
  docker_image:
    name: "{{ INFINISPAN_ENV_IMAGE }}"
    source: pull

- name: Run Infinispan
  docker_container:
    name: "{{ INFINISPAN_SERVER_NAME }}"
    image: "{{ INFINISPAN_ENV_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      MEM_OPTS: "-Xms{{ INFINISPAN_MEMORY }} -Xmx{{ INFINISPAN_MEMORY }}"
      JAVA_OPTIONS: "-Xms{{ INFINISPAN_MEMORY }} -Xmx{{ INFINISPAN_MEMORY }}"
      JAVA_OPTS: "-Xms{{ INFINISPAN_MEMORY }} -Xmx{{ INFINISPAN_MEMORY }}"
