- name: Pull Curation Data Image
  docker_image:
    name: "{{ CURATION_DATA_IMAGE }}"
    source: pull

- name: Run Curation Data Setup
  docker_container:
    name: "{{ CURATION_POSTGRES_SERVER_NAME }}"
    image: "{{ CURATION_DATA_IMAGE }}"
    detach: no
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "5432:5432"
    network_mode: "{{ NET }}"
  ignore_errors: true

- name: Run Curation Data Server
  docker_container:
    name: "{{ CURATION_POSTGRES_SERVER_NAME }}"
    image: "{{ CURATION_DATA_IMAGE }}"
    state: started
