- name: Pull Neo4j Data Image
  docker_image:
    name: "{{ NEO_DATA_IMAGE }}"
    source: pull

- name: Run Neo4j
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_DATA_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "7474:7474"
      - "7687:7687"
    network_mode: "{{ NET }}"
    env:
      #NEO4J_dbms_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      #NEO4J_dbms_memory_heap_maxSize: "{{ NEO_MAX_HEAP }}"
      NEO4J_AUTH: "none"

- pause:
    minutes: 2
