- name: Pull Intermine Tomcat Env Image
  docker_image:
    name: "{{ INTERMINE_TOMCAT_ENV_NAME }}"
    source: pull

- name: Run Tomcat
  docker_container:
    name: "{{ INTERMINE_TOMCAT_SERVER_NAME }}"
    image: "{{ INTERMINE_TOMCAT_ENV_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "8083:8080"
    network_mode: "{{ NET }}"
    env:
      JAVA_OPTS: "-Xmx2g -Xms1g"
