---

- name: Pull Nginx Server Image
  docker_image:
    name: "{{ REGISTRY }}/agr_nginx:{{ NET }}"

- name: Run Nginx
  docker_container:
    name: "agr.{{ NET }}.nginx.server"
    image: "{{ REGISTRY }}/agr_nginx:{{ NET }}"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: "{{ NET }}"
    env:
      API_URL: "http://{{ API_SERVER_NAME }}:8080"
    volumes:
      - /home/core/.htpasswd:/etc/nginx/.htpasswd
      - /home/core/ssl:/etc/ssl/certs