---
- name: Pull Java Run Image
  shell: docker pull {{ JAVA_SOFTWARE_RUN_IMAGE }} 2>&1

- name: Run API with Health Check
  docker_container:
    name: "{{ API_SERVER_NAME }}"
    image: "{{ JAVA_SOFTWARE_RUN_IMAGE }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    ports:
      - "8082:8080"
    network_mode: "{{ NET }}"
    command: java -jar agr_api/target/agr_api.jar
    timeout: 180
    env:
      NEO4J_HOST: "{{ NEO_SERVER_NAME }}"
      ES_HOST: "{{ ES_SERVER_NAME }}"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.alliancegenome.org/api/search_autocomplete?q=p"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
