- name: Pull Neo4j Test Image
  docker_image:
    name: "{{ NEO_DATA_BUILD_IMAGE }}_test"
    source: pull

- name: Run Neo4j Test Image
  docker_container:
    name: "{{ NEO_SERVER_NAME }}"
    image: "{{ NEO_DATA_BUILD_IMAGE }}_test"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOG_SERVER_ADDRESS }}"
    network_mode: "{{ NET }}"
    env:
      NEO4J_dbms_memory_pagecache_size: "{{ NEO_PAGE_CACHE }}"
      NEO4J_dbms_memory_heap_maxSize: "{{ NEO_MAX_HEAP }}"
      NEO4J_AUTH: "none"
