---

- name: Pull Apollo Server Image
  docker_image:
    name: "{{ APOLLO_SERVER_IMAGE_NAME }}"

- name: Run Apollo Server
  docker_container:
    name: "{{ APOLLO_SERVER_NAME }}"
    image: "{{ APOLLO_SERVER_IMAGE_NAME }}"
    log_driver: "gelf"
    log_options:
      gelf-address: "{{ LOGSTASH_SERVER_ADDRESS }}"
    networks:
      - name: "{{ NET }}"
    env:
      APOLLO_PATH: apollo
